### PR TITLE
Fix EE disabling on Samsung devices

### LINKED ISSUE #153: Cloning does not work (Galaxy S21 FE)
**Describe the bug**
After scanning a tag within nfcgate and bringing the phone near the reader, the reader does not accept it and gives messages like "put only one card near the reader" or "return the card to the reader and try again". While holding the phone near the reader, the reader beeps several times (like 2-3 per second) and displays an error.

I tried looking at the logcat output while holding the phone near the reader. I observed that the following lines appear in the log (with small differences, e.g. Acquired ID) every time the reader beeps:
```
02-19 20:21:08.044  3716  5935 I NATIVENFC: hook_NFA_Event: NFA_ACTIVATED_EVT(5) with status 1
02-19 20:21:08.044  3716  5935 D NATIVENFC: hook_ce_select_t4t()
02-19 20:21:08.044  3716  5935 D NATIVENFC: Patch enabled: 1
02-19 20:21:08.065  3716  5935 D NATIVENFC: hook_ce_select_t4t()
02-19 20:21:08.065  3716  5935 D NATIVENFC: Patch enabled: 1
02-19 20:21:08.073  1537  1549 I HYPER-HAL: [RequestManager.cpp]acquire(): Acquired ID : 6906186  [3716 / 0]    HINT : NFC_HCE    list : [TIMEOUT / 2000]
```

**App Information\***
Screenshot_20240223_040518_NFCGate

**Device Information\* (please complete the following information)**
Device: Samsung Galaxy S21 FE
OS: Android 14

**Log\***
[log6.txt](https://github.com/nfcgate/nfcgate/files/14380991/log6.txt)

### PR DESCRIPTION
**Pull request by kleest**
Fixes #153

### CODE REVIEW

File: nfcd/src/main/jni/src/helper/EEManager.cpp [hunk 1]
```diff
@@ -46,9 +46,9 @@ std::set<uint16_t> EEManager::findActiveEEs() const {
             LOGD("EE found: %x with {status=%d, ee_interface=[%s], la_protocol=%d, lb_protocol=%d, lf_protocol=%d}",
                  ee_handle, ee_status, str_ee_interfaces.c_str(), la_protocol, lb_protocol, lf_protocol);
 
-            // only non-deactivated proprietary EEs
+            // only non-deactivated proprietary EEs or EEs without an interface
             auto itProp = std::find(ee_interface.begin(), ee_interface.end(), NCI_NFCEE_INTERFACE_PROPRIETARY);
-            if (ee_status != NFA_EE_STATUS_INACTIVE && itProp != ee_interface.end())
+            if (ee_status != NFA_EE_STATUS_INACTIVE && (itProp != ee_interface.end() || ee_interface.empty()))
```
Comment (roussosalex) [inline nfcd/src/main/jni/src/helper/EEManager.cpp]: Second part of the condition should probably be extracted to variable for readability purposes.

**Review by roussosalex — CHANGES_REQUESTED** [review]

**Review by roussosalex — APPROVED** [review]
